default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "iDelivery.xcodeproj")
    build_app(workspace: "iDelivery.xcworkspace", scheme: "iDelivery")
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
    version = get_version_number
  end
end
